spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        #lb: load balancer
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customer/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  user:
    name: admin
    password: admin